"""initial

Revision ID: cd2cb1f132bb
Revises: 
Create Date: 2026-03-14 12:46:28.688133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd2cb1f132bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    orderstatus = postgresql.ENUM(
        'created', 'pending', 'in_progress', 'delivered', 'cancelled',
        name='orderstatus',
        create_type=False
    )
    orderstatus.create(op.get_bind(), checkfirst=True)

    op.create_table(
        'orders',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('customer_name', sa.String(), nullable=False),
        sa.Column('item_name', sa.String(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('status', postgresql.ENUM(
            'created', 'pending', 'in_progress', 'delivered', 'cancelled',
            name='orderstatus',
            create_type=False
        ), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS orderstatus")
